version: 2.1
jobs:
  build:
    docker:
      - image: ocaml/opam2:4.08
        environment:
          TERM: xterm
      - image: postgres:12.2
        environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: dev
      - image: mariadb:10.1.41-bionic
        environment:
          MYSQL_USER: admin
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: dev
          MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    steps:
      - run:
          name: Update opam
          command: |
            opam remote remove --all default
            opam remote add default https://opam.ocaml.org
      - checkout
      - run:
          name: Pin packages
          command: |
            opam pin add -y -n sihl .
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -y libmariadbclient-dev libpq-dev
            opam depext -y sihl
      - run:
          name: Install OCaml dependencies
          command: |
            opam install --deps-only -y sihl --with-test
      - run:
          name: Build
          command: opam config exec -- make
      - run:
          name: Install OCaml runtime dependencies
          command: opam install -y caqti-driver-postgresql caqti-driver-mariadb
      - run:
          name: Test
          command: opam config exec -- make test-all

workflows:
  version: 2
  build:
    jobs:
      - build
